package com.dfbz.dao;

import com.dfbz.domain.ComsAdmin;
import com.dfbz.domain.ComsAdminExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ComsAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_admin
     *
     * @mbg.generated
     */
    long countByExample(ComsAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_admin
     *
     * @mbg.generated
     */
    int deleteByExample(ComsAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_admin
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_admin
     *
     * @mbg.generated
     */
    int insert(ComsAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_admin
     *
     * @mbg.generated
     */
    int insertSelective(ComsAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ComsAdmin selectOneByExample(ComsAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ComsAdmin selectOneByExampleSelective(@Param("example") ComsAdminExample example, @Param("selective") ComsAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ComsAdmin> selectByExampleSelective(@Param("example") ComsAdminExample example, @Param("selective") ComsAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_admin
     *
     * @mbg.generated
     */
    List<ComsAdmin> selectByExample(ComsAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ComsAdmin selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ComsAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_admin
     *
     * @mbg.generated
     */
    ComsAdmin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_admin
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ComsAdmin record, @Param("example") ComsAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_admin
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ComsAdmin record, @Param("example") ComsAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ComsAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ComsAdmin record);
}