package com.dfbz.dao;

import com.dfbz.domain.ComsOrder;
import com.dfbz.domain.ComsOrderExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ComsOrderMapper {

    /**
     * 根据stallId查询哟用户订单
     * @param stallId
     * @return
     */
    List<ComsOrder> selectByPrimaryStallId(Integer stallId);
    /**
     * 根据stallId查询哟用户订单
     * @param supplierId
     * @return
     */
    List<ComsOrder> selectByPrimarySupplierId(Integer supplierId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_order
     *
     * @mbg.generated
     */
    long countByExample(ComsOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_order
     *
     * @mbg.generated
     */
    int deleteByExample(ComsOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_order
     *
     * @mbg.generated
     */
    int insert(ComsOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_order
     *
     * @mbg.generated
     */
    int insertSelective(ComsOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ComsOrder selectOneByExample(ComsOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ComsOrder selectOneByExampleSelective(@Param("example") ComsOrderExample example, @Param("selective") ComsOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ComsOrder> selectByExampleSelective(@Param("example") ComsOrderExample example, @Param("selective") ComsOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_order
     *
     * @mbg.generated
     */
    List<ComsOrder> selectByExample(ComsOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ComsOrder selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ComsOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_order
     *
     * @mbg.generated
     */
    ComsOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ComsOrder record, @Param("example") ComsOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ComsOrder record, @Param("example") ComsOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ComsOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ComsOrder record);
}