package com.dfbz.dao;

import com.dfbz.domain.ComsStall;
import com.dfbz.domain.ComsStallExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ComsStallMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_stall
     *
     * @mbg.generated
     */
    long countByExample(ComsStallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_stall
     *
     * @mbg.generated
     */
    int deleteByExample(ComsStallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_stall
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_stall
     *
     * @mbg.generated
     */
    int insert(ComsStall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_stall
     *
     * @mbg.generated
     */
    int insertSelective(ComsStall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_stall
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ComsStall selectOneByExample(ComsStallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_stall
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ComsStall selectOneByExampleSelective(@Param("example") ComsStallExample example, @Param("selective") ComsStall.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_stall
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ComsStall> selectByExampleSelective(@Param("example") ComsStallExample example, @Param("selective") ComsStall.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_stall
     *
     * @mbg.generated
     */
    List<ComsStall> selectByExample(ComsStallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_stall
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ComsStall selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ComsStall.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_stall
     *
     * @mbg.generated
     */
    ComsStall selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_stall
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ComsStall record, @Param("example") ComsStallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_stall
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ComsStall record, @Param("example") ComsStallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_stall
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ComsStall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_stall
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ComsStall record);
}