package com.dfbz.dao;

import com.dfbz.domain.ComsPriceList;
import com.dfbz.domain.ComsPriceListExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ComsPriceListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_price_list
     *
     * @mbg.generated
     */
    long countByExample(ComsPriceListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_price_list
     *
     * @mbg.generated
     */
    int deleteByExample(ComsPriceListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_price_list
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_price_list
     *
     * @mbg.generated
     */
    int insert(ComsPriceList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_price_list
     *
     * @mbg.generated
     */
    int insertSelective(ComsPriceList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_price_list
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ComsPriceList selectOneByExample(ComsPriceListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_price_list
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ComsPriceList selectOneByExampleSelective(@Param("example") ComsPriceListExample example, @Param("selective") ComsPriceList.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_price_list
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ComsPriceList> selectByExampleSelective(@Param("example") ComsPriceListExample example, @Param("selective") ComsPriceList.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_price_list
     *
     * @mbg.generated
     */
    List<ComsPriceList> selectByExample(ComsPriceListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_price_list
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ComsPriceList selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ComsPriceList.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_price_list
     *
     * @mbg.generated
     */
    ComsPriceList selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_price_list
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ComsPriceList record, @Param("example") ComsPriceListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_price_list
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ComsPriceList record, @Param("example") ComsPriceListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_price_list
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ComsPriceList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_price_list
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ComsPriceList record);
}