package com.dfbz.dao;

import com.dfbz.domain.ComsErrOrder;
import com.dfbz.domain.ComsErrOrderExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ComsErrOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_err_order
     *
     * @mbg.generated
     */
    long countByExample(ComsErrOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_err_order
     *
     * @mbg.generated
     */
    int deleteByExample(ComsErrOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_err_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_err_order
     *
     * @mbg.generated
     */
    int insert(ComsErrOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_err_order
     *
     * @mbg.generated
     */
    int insertSelective(ComsErrOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_err_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ComsErrOrder selectOneByExample(ComsErrOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_err_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ComsErrOrder selectOneByExampleSelective(@Param("example") ComsErrOrderExample example, @Param("selective") ComsErrOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_err_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ComsErrOrder> selectByExampleSelective(@Param("example") ComsErrOrderExample example, @Param("selective") ComsErrOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_err_order
     *
     * @mbg.generated
     */
    List<ComsErrOrder> selectByExample(ComsErrOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_err_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ComsErrOrder selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ComsErrOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_err_order
     *
     * @mbg.generated
     */
    ComsErrOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_err_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ComsErrOrder record, @Param("example") ComsErrOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_err_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ComsErrOrder record, @Param("example") ComsErrOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_err_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ComsErrOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_err_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ComsErrOrder record);
}