package com.dfbz.dao;

import com.dfbz.domain.ComsSupCategory;
import com.dfbz.domain.ComsSupCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ComsSupCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_sup_category
     *
     * @mbg.generated
     */
    long countByExample(ComsSupCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_sup_category
     *
     * @mbg.generated
     */
    int deleteByExample(ComsSupCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_sup_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_sup_category
     *
     * @mbg.generated
     */
    int insert(ComsSupCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_sup_category
     *
     * @mbg.generated
     */
    int insertSelective(ComsSupCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_sup_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ComsSupCategory selectOneByExample(ComsSupCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_sup_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ComsSupCategory selectOneByExampleSelective(@Param("example") ComsSupCategoryExample example, @Param("selective") ComsSupCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_sup_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ComsSupCategory> selectByExampleSelective(@Param("example") ComsSupCategoryExample example, @Param("selective") ComsSupCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_sup_category
     *
     * @mbg.generated
     */
    List<ComsSupCategory> selectByExample(ComsSupCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_sup_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ComsSupCategory selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ComsSupCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_sup_category
     *
     * @mbg.generated
     */
    ComsSupCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_sup_category
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ComsSupCategory record, @Param("example") ComsSupCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_sup_category
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ComsSupCategory record, @Param("example") ComsSupCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_sup_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ComsSupCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_sup_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ComsSupCategory record);
}