package com.dfbz.dao;

import com.dfbz.domain.ComsCartItem;
import com.dfbz.domain.ComsCartItemExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ComsCartItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_cart_item
     *
     * @mbg.generated
     */
    long countByExample(ComsCartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_cart_item
     *
     * @mbg.generated
     */
    int deleteByExample(ComsCartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_cart_item
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_cart_item
     *
     * @mbg.generated
     */
    int insert(ComsCartItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_cart_item
     *
     * @mbg.generated
     */
    int insertSelective(ComsCartItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_cart_item
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ComsCartItem selectOneByExample(ComsCartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_cart_item
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ComsCartItem selectOneByExampleSelective(@Param("example") ComsCartItemExample example, @Param("selective") ComsCartItem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_cart_item
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ComsCartItem> selectByExampleSelective(@Param("example") ComsCartItemExample example, @Param("selective") ComsCartItem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_cart_item
     *
     * @mbg.generated
     */
    List<ComsCartItem> selectByExample(ComsCartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_cart_item
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ComsCartItem selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ComsCartItem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_cart_item
     *
     * @mbg.generated
     */
    ComsCartItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_cart_item
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ComsCartItem record, @Param("example") ComsCartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_cart_item
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ComsCartItem record, @Param("example") ComsCartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_cart_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ComsCartItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_cart_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ComsCartItem record);
}