package com.dfbz.dao;

import com.dfbz.domain.ComsCategory;
import com.dfbz.domain.ComsCategoryExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ComsCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_category
     *
     * @mbg.generated
     */
    long countByExample(ComsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_category
     *
     * @mbg.generated
     */
    int deleteByExample(ComsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_category
     *
     * @mbg.generated
     */
    int insert(ComsCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_category
     *
     * @mbg.generated
     */
    int insertSelective(ComsCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ComsCategory selectOneByExample(ComsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ComsCategory selectOneByExampleSelective(@Param("example") ComsCategoryExample example, @Param("selective") ComsCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ComsCategory> selectByExampleSelective(@Param("example") ComsCategoryExample example, @Param("selective") ComsCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_category
     *
     * @mbg.generated
     */
    List<ComsCategory> selectByExample(ComsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ComsCategory selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ComsCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_category
     *
     * @mbg.generated
     */
    ComsCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_category
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ComsCategory record, @Param("example") ComsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_category
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ComsCategory record, @Param("example") ComsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ComsCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coms_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ComsCategory record);
}