#markerhub:
#  jwt:
#    secret: f4e2e52034348f86b67cde581c0f9eb5
#    expire: 604800
#    header: Authorization
#server:
#  port: 8080
#shiro-redis:
#  enable: true
#  redis-manager:
#    host: 127.0.0.1:6379
spring:
  thymeleaf:
    cache: false
